data-types
js-tasks-ru/js-20201030_artem720 pull request #2
Opened 2020-11-05 18:23 UTC by irontir

2020-11-05 19:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
- should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

2020-11-06 05:04 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-06 14:39 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +            return a.localeCompare(b,  ['ru', 'en'],{caseFirst:'upper'})
строка 11 дублирует строку 13 за исключением порядка аргументов в методе `localeCompare`. Нужно избавиться от дублирующего кода.

2020-11-06 14:39 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-11-06 15:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-09 12:13 UTC, dosandk approved these changes

2020-11-09 12:14 UTC, merged